export interface Mandal {
  id: string;
  rank: number;
  name: string;
  marathiName: string;
  area: string;
  address: string;
  description: string;
  established: string;
  famousFor: string;
  crowdLevel: "Extreme" | "Very High" | "High" | "Moderate";
  bestTimeToVisit: string;
  durationDays: number;
  lat: number;
  lng: number;
  mapsUrl: string;
  directionsUrl: string;
  nearbyStation: string;
  tips: string;
  color: string;
}

export const MUMBAI_TOP_MANDALS: Mandal[] = [
  {
    id: "lalbaugcha-raja",
    rank: 1,
    name: "Lalbaugcha Raja",
    marathiName: "लालबागचा राजा",
    area: "Lalbaug, Mumbai",
    address: "Putlabai Chawl, Lalbaug, Mumbai – 400012",
    description: "The most celebrated Ganpati in the world, known as the 'King of Lalbaug'. Millions of devotees queue for darshan every year, with waiting times exceeding 24 hours. Famous for granting wishes and its stunning gold-adorned idol.",
    established: "1934",
    famousFor: "Wish-fulfilling deity, Gold & diamond ornaments, Massive procession",
    crowdLevel: "Extreme",
    bestTimeToVisit: "Early morning 4–6 AM or late night 12–2 AM",
    durationDays: 10,
    lat: 18.9997,
    lng: 72.8341,
    mapsUrl: "https://maps.google.com/?q=Lalbaugcha+Raja,Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Lalbaugcha+Raja+Sarvajanik+Ganeshotsav+Mandal,+Putlabai+Chawl,+Lalbaug,+Mumbai/@18.9997,72.8341,15z",
    nearbyStation: "Curry Road (Harbour Line)",
    tips: "Book a priority pass in advance. Wear comfortable shoes — queue is 3–5 km long. Carry water.",
    color: "#B45309",
  },
  {
    id: "siddhivinayak",
    rank: 2,
    name: "Siddhivinayak Temple",
    marathiName: "श्री सिद्धिविनायक मंदिर",
    area: "Prabhadevi, Mumbai",
    address: "S.K. Bole Marg, Prabhadevi, Mumbai – 400028",
    description: "One of India's wealthiest and most visited temples. The black stone idol of Siddhivinayak is 200+ years old. The temple attracts Bollywood stars, politicians, and millions of devotees during Chaturthi.",
    established: "1801",
    famousFor: "Ancient black-stone idol, 200-year history, Celebrity visits",
    crowdLevel: "Extreme",
    bestTimeToVisit: "Tuesdays early morning (5–7 AM) or midnight darshan",
    durationDays: 11,
    lat: 19.0171,
    lng: 72.8302,
    mapsUrl: "https://maps.google.com/?q=Siddhivinayak+Temple+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Shree+Siddhivinayak+Temple,+S.K.+Bole+Marg,+Prabhadevi,+Mumbai/@19.0171,72.8302,15z",
    nearbyStation: "Dadar (Central & Western Line)",
    tips: "Security is strict — no bags allowed. Use temple's cloak room. Arrive before sunrise.",
    color: "#D97706",
  },
  {
    id: "ganesha-galli",
    rank: 3,
    name: "Ganesh Galli Cha Murti",
    marathiName: "गणेश गल्लीचा मुर्ती",
    area: "Lalbaug, Mumbai",
    address: "Ganesh Galli, Lalbaug, Mumbai – 400012",
    description: "Just a lane away from Lalbaugcha Raja, this mandal recreates iconic Indian monuments every year as a backdrop for the idol. The breathtaking thematic decorations draw huge crowds.",
    established: "1928",
    famousFor: "Spectacular thematic decorations, Life-size replicas of monuments",
    crowdLevel: "Very High",
    bestTimeToVisit: "Evening 8–11 PM for the best lighting",
    durationDays: 10,
    lat: 19.0012,
    lng: 72.8335,
    mapsUrl: "https://maps.google.com/?q=Ganesh+Galli+Mumbai+Ganpati",
    directionsUrl: "https://www.google.com/maps/dir//Ganesh+Galli+Lalbaug+Mumbai/@19.0012,72.8335,16z",
    nearbyStation: "Curry Road (Harbour Line)",
    tips: "Visit at night for the spectacular LED decor. Combines well with Lalbaugcha Raja visit.",
    color: "#B45309",
  },
  {
    id: "andhericha-raja",
    rank: 4,
    name: "Andhericha Raja",
    marathiName: "अंधेरीचा राजा",
    area: "Andheri West, Mumbai",
    address: "DN Nagar, Andheri West, Mumbai – 400053",
    description: "Known as the 'King of Andheri', this mandal is a favourite of Bollywood celebrities who live nearby. The idol is dressed in extravagant gold jewellery. Queue management is excellent.",
    established: "1966",
    famousFor: "Bollywood celebrity visits, Ornate gold jewellery, Efficient darshan",
    crowdLevel: "Very High",
    bestTimeToVisit: "Afternoon 2–5 PM on weekdays",
    durationDays: 10,
    lat: 19.1197,
    lng: 72.8318,
    mapsUrl: "https://maps.google.com/?q=Andhericha+Raja+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Andhericha+Raja+Sarvajanik+Utsav+Mandal/@19.1197,72.8318,15z",
    nearbyStation: "Andheri (Western Line / Metro Line 1)",
    tips: "Close to Versova Beach — plan an evening visit combo. Celebrity sightings are common!",
    color: "#92400E",
  },
  {
    id: "gsb-seva-mandal",
    rank: 5,
    name: "GSB Seva Mandal",
    marathiName: "जीएसबी सेवा मंडल",
    area: "Matunga / King's Circle, Mumbai",
    address: "GSB Seva Mandal, King's Circle, Matunga, Mumbai – 400019",
    description: "The most expensive Ganpati in India. GSB Seva Mandal's idol is adorned with gold and silver ornaments worth hundreds of crores. The idol itself weighs several kilograms in gold.",
    established: "1954",
    famousFor: "Gold & silver ornaments worth 100+ crore, Most expensive Ganpati",
    crowdLevel: "Very High",
    bestTimeToVisit: "Morning 6–9 AM",
    durationDays: 5,
    lat: 19.0233,
    lng: 72.8645,
    mapsUrl: "https://maps.google.com/?q=GSB+Seva+Mandal+Kings+Circle+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//GSB+Seva+Mandal,+King%27s+Circle,+Matunga,+Mumbai/@19.0233,72.8645,15z",
    nearbyStation: "King's Circle (Harbour Line)",
    tips: "Gold security is extremely tight. Photography of ornaments may be restricted. Go early.",
    color: "#D97706",
  },
  {
    id: "chinchpoklicha-chintamani",
    rank: 6,
    name: "Chinchpoklicha Chintamani",
    marathiName: "चिंचपोकळीचा चिंतामणी",
    area: "Chinchpokli, Mumbai",
    address: "Chinchpokli, Mumbai – 400012",
    description: "One of the oldest and most revered mandals in Mumbai. The idol is known for its extremely serene and calming expression. Devotees from across Maharashtra make special trips here.",
    established: "1920",
    famousFor: "Serene idol, Ancient mandal, Maharashtra-wide fame",
    crowdLevel: "High",
    bestTimeToVisit: "Early morning or late evening",
    durationDays: 10,
    lat: 18.9986,
    lng: 72.8416,
    mapsUrl: "https://maps.google.com/?q=Chinchpoklicha+Chintamani+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Chinchpoklicha+Chintamani+Mandal,+Mumbai/@18.9986,72.8416,15z",
    nearbyStation: "Chinchpokli (Central Line)",
    tips: "Pair with Lalbaugcha Raja and Ganesh Galli as they are all within 2 km of each other.",
    color: "#92400E",
  },
  {
    id: "keshavji-naik-chawl",
    rank: 7,
    name: "Keshavji Naik Chawl",
    marathiName: "केशवजी नाईक चाळ",
    area: "Girgaon, Mumbai",
    address: "Keshavji Naik Chawl, Girgaon, Mumbai – 400004",
    description: "The oldest Ganpati mandal in Mumbai. This mandal started the tradition of public Ganesh Utsav in 1893 following Lokmanya Bal Gangadhar Tilak's call. A pilgrimage of historical significance.",
    established: "1893",
    famousFor: "Oldest Ganpati in Mumbai, Tilak's original public utsav mandal",
    crowdLevel: "High",
    bestTimeToVisit: "Any time of day — less crowded than South Mumbai mandals",
    durationDays: 10,
    lat: 18.9638,
    lng: 72.8152,
    mapsUrl: "https://maps.google.com/?q=Keshavji+Naik+Chawl+Girgaon+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Keshavji+Naik+Chawl,+Girgaon,+Mumbai/@18.9638,72.8152,15z",
    nearbyStation: "Grant Road (Western Line)",
    tips: "Rich historical significance. Visit for a peaceful, authentic darshan without extreme crowds.",
    color: "#B45309",
  },
  {
    id: "tejukayacha-raja",
    rank: 8,
    name: "Tejukayacha Raja",
    marathiName: "तेजुकायाचा राजा",
    area: "Lalbaug, Mumbai",
    address: "Tejukaya, Lalbaug, Mumbai – 400012",
    description: "Located in the Lalbaug belt, this mandal is known for its creative and uniquely artistic idol presentations each year. The route passes through the vibrant Lalbaug market area.",
    established: "1942",
    famousFor: "Artistic idol themes, Lalbaug belt celebration atmosphere",
    crowdLevel: "High",
    bestTimeToVisit: "Evening 7–10 PM",
    durationDays: 10,
    lat: 19.0005,
    lng: 72.8352,
    mapsUrl: "https://maps.google.com/?q=Tejukayacha+Raja+Mumbai",
    directionsUrl: "https://www.google.com/maps/dir//Tejukayacha+Raja+Mumbai/@19.0005,72.8352,16z",
    nearbyStation: "Curry Road (Harbour Line)",
    tips: "Part of the Lalbaug Ganpati trail. Visit multiple mandals in one walk along Lalbaug Road.",
    color: "#78350F",
  },
];

export const CROWD_COLORS: Record<Mandal["crowdLevel"], string> = {
  "Extreme": "#DC2626",
  "Very High": "#EA580C",
  "High": "#D97706",
  "Moderate": "#16A34A",
};

export const CROWD_WAIT: Record<Mandal["crowdLevel"], string> = {
  "Extreme": "10–30+ hrs",
  "Very High": "4–10 hrs",
  "High": "1–4 hrs",
  "Moderate": "30–60 min",
};
